In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl

In [2]:
Data = pd.read_csv("../Data/Raw/final_records.csv")

In [3]:
Data

,date,day_of_sale,week_of_year,year_of_sales,weeks_of_year,shop_id,shop_name,customers,sales_usd,avg_sales_per_person,pct_family,pct_female,pct_male,pct_single,avg_temp_f,humidity_pct,is_rain,precip_in
0,2023-01-01,Sunday,1,2023,Weekends,4,Jacksonville,250,3972.40,15.89,49.4,52.1,47.9,50.6,77.9,46.3,0,0.00
1,2023-01-01,Sunday,1,2023,Weekends,2,Orlando,289,4887.88,16.91,49.4,52.1,47.9,50.6,77.9,46.3,0,0.00
2,2023-01-01,Sunday,1,2023,Weekends,1,Miami Beach,296,5440.48,18.38,49.4,52.1,47.9,50.6,77.9,46.3,0,0.00
3,2023-01-01,Sunday,1,2023,Weekends,3,Tampa,225,3716.96,16.52,49.4,52.1,47.9,50.6,77.9,46.3,0,0.00
4,2023-01-02,Monday,1,2023,Weekdays,4,Jacksonville,189,2805.14,14.84,45.6,52.6,47.4,54.4,73.9,51.1,1,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2919,2024-12-30,Monday,52,2024,Weekdays,2,Orlando,218,3843.00,17.63,46.1,51.1,48.9,53.9,75.5,39.3,1,0.48
2920,2024-12-31,Tuesday,52,2024,Weekdays,3,Tampa,155,2844.47,18.35,43.8,49.8,50.2,56.2,70.9,47.8,0,0.00
2921,2024-12-31,Tuesday,52,2024,Weekdays,4,Jacksonville,166,2603.55,15.68,43.8,49.8,50.2,56.2,70.9,47.8,0,0.00
2922,2024-12-31,Tuesday,52,2024,Weekdays,2,Orlando,239,4092.22,17.12,43.8,49.8,50.2,56.2,70.9,47.8,0,0.00
2923,2024-12-31,Tuesday,52,2024,Weekdays,1,Miami Beach,196,3755.53,19.16,43.8,49.8,50.2,56.2,70.9,47.8,0,0.00

In [5]:
print(Data.columns)

Index(['date', 'day_of_sale', 'week_of_year', 'year_of_sales', 'weeks_of_year',
       'shop_id', 'shop_name', 'customers', 'sales_usd',
       'avg_sales_per_person', 'pct_family', 'pct_female', 'pct_male',
       'pct_single', 'avg_temp_f', 'humidity_pct', 'is_rain', 'precip_in'],
      dtype='str')

In [6]:
# Dataset Overview
display(pd.DataFrame({
    "Column": Data.columns,
    "Data Type": Data.dtypes.values,
    "Missing Values": Data.isnull().sum().values,
    "Unique Values": Data.nunique().values
}))

                  Column Data Type  Missing Values  Unique Values
0                   date       str               0            731
1            day_of_sale       str               0              7
2           week_of_year     int64               0             54
3          year_of_sales     int64               0              2
4          weeks_of_year       str               0              2
5                shop_id     int64               0              4
6              shop_name       str               0              4
7              customers     int64               0            249
8              sales_usd   float64               0           2909
9   avg_sales_per_person   float64               0            615
10            pct_family   float64               0            136
11            pct_female   float64               0             96
12              pct_male   float64               0             96
13            pct_single   float64               0            136
14            avg_temp_f   float64               0            293
15          humidity_pct   float64               0            362
16               is_rain     int64               0              2
17             precip_in   float64               0            138

In [7]:
Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2924 entries, 0 to 2923
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  2924 non-null   str
 1   day_of_sale           2924 non-null   str
 2   week_of_year          2924 non-null   int64
 3   year_of_sales         2924 non-null   int64
 4   weeks_of_year         2924 non-null   str
 5   shop_id               2924 non-null   int64
 6   shop_name             2924 non-null   str
 7   customers             2924 non-null   int64
 8   sales_usd             2924 non-null   float64
 9   avg_sales_per_person  2924 non-null   float64
 10  pct_family            2924 non-null   float64
 11  pct_female            2924 non-null   float64
 12  pct_male              2924 non-null   float64
 13  pct_single            2924 non-null   float64
 14  avg_temp_f            2924 non-null   float64
 15  humidity_pct          2924 non-null   float64
 16  is_rain               2924 non-null   int64
 17  precip_in             2924 non-null   float64
dtypes: float64(9), int64(5), str(4)
memory usage: 508.1 KB

In [8]:
Data

,date,day_of_sale,week_of_year,year_of_sales,weeks_of_year,shop_id,shop_name,customers,sales_usd,avg_sales_per_person,pct_family,pct_female,pct_male,pct_single,avg_temp_f,humidity_pct,is_rain,precip_in
0,2023-01-01,Sunday,1,2023,Weekends,4,Jacksonville,250,3972.40,15.89,49.4,52.1,47.9,50.6,77.9,46.3,0,0.00
1,2023-01-01,Sunday,1,2023,Weekends,2,Orlando,289,4887.88,16.91,49.4,52.1,47.9,50.6,77.9,46.3,0,0.00
2,2023-01-01,Sunday,1,2023,Weekends,1,Miami Beach,296,5440.48,18.38,49.4,52.1,47.9,50.6,77.9,46.3,0,0.00
3,2023-01-01,Sunday,1,2023,Weekends,3,Tampa,225,3716.96,16.52,49.4,52.1,47.9,50.6,77.9,46.3,0,0.00
4,2023-01-02,Monday,1,2023,Weekdays,4,Jacksonville,189,2805.14,14.84,45.6,52.6,47.4,54.4,73.9,51.1,1,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2919,2024-12-30,Monday,52,2024,Weekdays,2,Orlando,218,3843.00,17.63,46.1,51.1,48.9,53.9,75.5,39.3,1,0.48
2920,2024-12-31,Tuesday,52,2024,Weekdays,3,Tampa,155,2844.47,18.35,43.8,49.8,50.2,56.2,70.9,47.8,0,0.00
2921,2024-12-31,Tuesday,52,2024,Weekdays,4,Jacksonville,166,2603.55,15.68,43.8,49.8,50.2,56.2,70.9,47.8,0,0.00
2922,2024-12-31,Tuesday,52,2024,Weekdays,2,Orlando,239,4092.22,17.12,43.8,49.8,50.2,56.2,70.9,47.8,0,0.00
2923,2024-12-31,Tuesday,52,2024,Weekdays,1,Miami Beach,196,3755.53,19.16,43.8,49.8,50.2,56.2,70.9,47.8,0,0.00

In [9]:
Data["week_of_year"].sort_values().unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

In [10]:
Data[Data["week_of_year"] == 0][["date", "week_of_year"]]

            date  week_of_year
1460  2024-01-01             0
1461  2024-01-01             0
1462  2024-01-01             0
1463  2024-01-01             0
1464  2024-01-02             0
1465  2024-01-02             0
1466  2024-01-02             0
1467  2024-01-02             0
1468  2024-01-03             0
1469  2024-01-03             0
1470  2024-01-03             0
1471  2024-01-03             0
1472  2024-01-04             0
1473  2024-01-04             0
1474  2024-01-04             0
1475  2024-01-04             0
1476  2024-01-05             0
1477  2024-01-05             0
1478  2024-01-05             0
1479  2024-01-05             0
1480  2024-01-06             0
1481  2024-01-06             0
1482  2024-01-06             0
1483  2024-01-06             0